[2024-11-28T11:44:29.711+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: snowflake_demo_dag.query_data manual__2024-11-28T11:44:22.917117+00:00 [queued]>
[2024-11-28T11:44:29.716+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: snowflake_demo_dag.query_data manual__2024-11-28T11:44:22.917117+00:00 [queued]>
[2024-11-28T11:44:29.716+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-11-28T11:44:29.716+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 11
[2024-11-28T11:44:29.716+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-11-28T11:44:29.723+0000] {taskinstance.py:1383} INFO - Executing <Task(SnowflakeOperator): query_data> on 2024-11-28 11:44:22.917117+00:00
[2024-11-28T11:44:29.726+0000] {standard_task_runner.py:55} INFO - Started process 775 to run task
[2024-11-28T11:44:29.728+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'snowflake_demo_dag', 'query_data', 'manual__2024-11-28T11:44:22.917117+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_dag.py', '--cfg-path', '/tmp/tmp0ddmoxtb']
[2024-11-28T11:44:29.728+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask query_data
[2024-11-28T11:44:29.758+0000] {task_command.py:376} INFO - Running <TaskInstance: snowflake_demo_dag.query_data manual__2024-11-28T11:44:22.917117+00:00 [running]> on host 0270f4f4bd85
[2024-11-28T11:44:29.790+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=snowflake_demo_dag
AIRFLOW_CTX_TASK_ID=query_data
AIRFLOW_CTX_EXECUTION_DATE=2024-11-28T11:44:22.917117+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-28T11:44:22.917117+00:00
[2024-11-28T11:44:29.791+0000] {sql.py:265} INFO - Executing: 
SELECT * FROM demo_table;
[2024-11-28T11:44:29.795+0000] {base.py:71} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2024-11-28T11:44:30.078+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/snowflake/connector/options.py:109: UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  "pyarrow", installed_pyarrow_version, pandas_pyarrow_extra

[2024-11-28T11:44:30.215+0000] {base.py:71} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2024-11-28T11:44:30.216+0000] {connection.py:300} INFO - Snowflake Connector for Python Version: 3.0.4, Python Version: 3.7.15, Platform: Linux-6.10.4-linuxkit-aarch64-with-debian-11.5
[2024-11-28T11:44:30.216+0000] {connection.py:1013} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-28T11:44:30.216+0000] {connection.py:1030} INFO - Setting use_openssl_only mode to False
[2024-11-28T11:44:30.609+0000] {cursor.py:806} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-11-28T11:44:30.697+0000] {cursor.py:819} INFO - query execution done
[2024-11-28T11:44:30.698+0000] {cursor.py:962} INFO - Number of results in first chunk: 1
[2024-11-28T11:44:30.700+0000] {sql.py:375} INFO - Running statement: SELECT * FROM demo_table;, parameters: None
[2024-11-28T11:44:30.701+0000] {cursor.py:806} INFO - query: [SELECT * FROM demo_table;]
[2024-11-28T11:44:30.870+0000] {cursor.py:819} INFO - query execution done
[2024-11-28T11:44:30.871+0000] {cursor.py:962} INFO - Number of results in first chunk: 5
[2024-11-28T11:44:30.871+0000] {sql.py:384} INFO - Rows affected: 5
[2024-11-28T11:44:30.874+0000] {snowflake.py:391} INFO - Rows affected: 5
[2024-11-28T11:44:30.874+0000] {snowflake.py:392} INFO - Snowflake query id: 01b8ac20-0001-3904-0006-ac5e0001b3b2
[2024-11-28T11:44:30.874+0000] {cursor.py:806} INFO - query: [COMMIT]
[2024-11-28T11:44:30.954+0000] {cursor.py:819} INFO - query execution done
[2024-11-28T11:44:30.955+0000] {cursor.py:962} INFO - Number of results in first chunk: 1
[2024-11-28T11:44:30.955+0000] {connection.py:605} INFO - closed
[2024-11-28T11:44:31.000+0000] {connection.py:608} INFO - No async queries seem to be running, deleting session
[2024-11-28T11:44:31.058+0000] {xcom.py:600} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-11-28T11:44:31.059+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2385, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 212, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 597, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
[2024-11-28T11:44:31.065+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=snowflake_demo_dag, task_id=query_data, execution_date=20241128T114422, start_date=20241128T114429, end_date=20241128T114431
[2024-11-28T11:44:31.074+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task query_data (Object of type datetime is not JSON serializable; 775)
[2024-11-28T11:44:31.120+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-11-28T11:44:31.132+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
